name: u
description: The only package you need, a complete set of packages and utilities you need in every single project.
version: 1.5.0
homepage: https://sinamn75.com
repository: https://github.com/SinaMN75/Utilities-flutter
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.10.0"
  flutter: ">=3.38.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4
  webview_flutter: ^4.13.1
  local_auth: ^3.0.0
  flutter_svg: ^2.2.3
  image_picker: ^1.2.1
  share_plus: ^12.0.1
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.3.0
  encrypt: ^5.0.3
  get: ^4.7.3
  flutter_map: ^8.2.2
  flutter_map_location_marker: ^10.2.0
  geolocator: ^14.0.2
  lottie: ^3.3.2
  image_cropper: ^11.0.0
  file_picker: ^10.3.9
  flutter_local_notifications: ^20.0.0
  syncfusion_flutter_charts: ^32.1.25
  syncfusion_flutter_barcodes: ^32.1.25
  syncfusion_flutter_gauges: ^32.1.25
  syncfusion_flutter_chat: ^32.1.25

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/fonts/
    - lib/assets/flags/
  fonts:
    - family: Vazir
      fonts:
        - asset: lib/assets/fonts/Vazir.ttf
    - family: Samim
      fonts:
        - asset: lib/assets/fonts/Samim.ttf
    - family: Shabnam
      fonts:
        - asset: lib/assets/fonts/Shabnam.ttf
    - family: Sahel
      fonts:
        - asset: lib/assets/fonts/Sahel.ttf
    - family: Yekan
      fonts:
        - asset: lib/assets/fonts/Yekan.ttf
    - family: IranSansFaNum
      fonts:
        - asset: lib/assets/fonts/IranSansFaNum.ttf

flutter_intl:
  enabled: true

#  flutter pub global activate rename
#  flutter pub global run rename setBundleId --value ""
#  flutter pub global run rename setAppName --value ""
#  flutter pub run flutter_launcher_icons:main

#Android only:
#  flutter build apk --target-platform android-arm64,android-arm --release && cp build/app/outputs/flutter-apk/app-release.apk ~/Desktop/

#Web only:
#  flutter build web --release && cd build/web && zip -r web.zip . && cd - && cp build/web/web.zip ~/Desktop/

#Web and ftp:
#  flutter build web --release && cd build/web && lftp -u sinapp_sinamn75_com,sinapp_sinamn75_com ftp://46.249.98.145:21 -e "set ssl:verify-certificate no; mirror -R ./ ./; bye"

#macOS only:
#  flutter build macos --release && cd build/macos/Build/Products/Release/ && zip -r sinapp.zip sinapp.app && cd - && cp build/macos/Build/Products/Release/sinapp.zip ~/Desktop/

#Android + Web:
#  flutter build apk --target-platform android-arm64,android-arm --release && flutter build web --release && cd build/web && zip -r web.zip . && cd - && cp build/app/outputs/flutter-apk/app-release.apk build/web/web.zip ~/Desktop/

#Android + macOS:
#  flutter build apk --target-platform android-arm64,android-arm --release && flutter build macos --release && cd build/macos/Build/Products/Release/ && zip -r sinapp.zip sinapp.app && cd - && cp build/app/outputs/flutter-apk/app-release.apk build/macos/Build/Products/Release/sinapp.zip ~/Desktop/

#All 3 platforms:
#  flutter clean && flutter build apk --target-platform android-arm64,android-arm --release && flutter build macos --release && flutter build web --release && cd build/macos/Build/Products/Release/ && zip -r sinapp.zip sinapp.app && cd - && cd build/web && zip -r web.zip . && cd - && cp build/app/outputs/flutter-apk/app-release.apk build/macos/Build/Products/Release/sinapp.zip build/web/web.zip ~/Desktop/