name: u
description: The only package you need, a complete set of packages and utilities you need in every single project.
version: 1.5.0
homepage: https://sinamn75.com
repository: https://github.com/SinaMN75/Utilities-flutter
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.10.0"
  flutter: ">=3.38.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  webview_flutter: ^4.13.0
  local_auth: ^3.0.0
  flutter_svg: ^2.2.3
  image_picker: ^1.2.1
  chewie: ^1.13.0
  share_plus: ^12.0.1
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.3.0
  encrypt: ^5.0.3

  get: ^4.7.3
  flutter_map: ^8.2.2
  flutter_map_location_marker: ^10.1.0
  geolocator: ^14.0.2
  lottie: ^3.3.2
  image_cropper: ^11.0.0
  file_picker: ^10.3.7
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.5.0
  easy_sidemenu: ^0.7.1
  syncfusion_flutter_charts: ^31.2.15
  syncfusion_flutter_barcodes: ^31.2.15
  syncfusion_flutter_signaturepad: ^31.2.15
  syncfusion_flutter_gauges: ^31.2.15
  syncfusion_flutter_chat: ^31.2.15
  syncfusion_flutter_calendar: ^31.2.15

  any_link_preview: ^3.0.3
  universal_html: ^2.3.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/fonts/
    - lib/assets/flags/
  fonts:
    - family: Vazir
      fonts:
        - asset: lib/assets/fonts/Vazir.ttf
    - family: Samim
      fonts:
        - asset: lib/assets/fonts/Samim.ttf
    - family: Shabnam
      fonts:
        - asset: lib/assets/fonts/Shabnam.ttf
    - family: Sahel
      fonts:
        - asset: lib/assets/fonts/Sahel.ttf
    - family: Yekan
      fonts:
        - asset: lib/assets/fonts/Yekan.ttf
    - family: IranSansFaNum
      fonts:
        - asset: lib/assets/fonts/IranSansFaNum.ttf
